plugins/process.py

* edge layers are not excluded in v7
* use orientation as degrees
Probably it makes sense to maintain this as a separate branch for now.

Fixes for KiCad 7 nightly compatibility

---

plugins/process.py

This just adds `if len() > 0:` before writing each CSV, to prevent crashing when the boards have no components (mechanical boards, RF, etc).
In some cases there can be designators without having BOM/positions (i.e. only drills, PCB antennas), or even just copper traces & vias (no BOM + no designators + no positions).
Thank you for this plugin, it is very useful! :+1:

Skip CSVs when there are no components or designators

---

README.md
plugins/process.py

Hiya!
I use **[uPesy/easyeda2kicad.py](https://github.com/uPesy/easyeda2kicad.py)** to download and convert footprints, symbols, and 3D models from JLCPCB/LCSC and noticed that the field that gets populated from that tool was just ever so slightly different from what Fabrication Toolkit looks for, so I've added that field to make that workflow even easier!
I've been doing a find-and-replace for now, but having the Fabrication Toolkit magically handle things would make that flow so much smoother.
Here's the field that gets set in `easyeda2kicad.py`: 
https://github.com/uPesy/easyeda2kicad.py/blob/92088a460fddaa6d266b28be507c863f5635e8c6/easyeda2kicad/kicad/parameters_kicad_symbol.py#L305
Thanks for the awesome tool!

Add new symbol field support for easyeda2kicad.py

---

plugins/process.py

Previously, the encoding of output files was UTF-8. However, this resulted in characters such as 'μ' and 'Ω' being garbled when the file was submitted. Therefore, the encoding of the output file was changed to UTF-8 with BOM.

Change encoding of output files to UTF-8 with BOM

---

plugins/process.py

This fix seems to work to keep almost-similar parts separate.
Closes #45

Don't merge similar components with different LCSC part numbers

---

README.md

I was having the same problem as presented in #41 and realized that I needed to update the PCB after entering a rotation offset in the Schematic Editor. This PR adds documentation to point this out and help others avoid the same frustration.

Explain the need to update PCB after adding rotation/position offset

---

plugins/process.py

Inverting around 360 degrees looked fine for angles, even 45 degrees and 10 degrees and so on, but turns out it actually needs inverting around 180 degrees else your diodes are all backwards. Arrrg. Sorry about that.
Screen shots of some diodes, all done with no JLCPCB Rotation Offset set, comparing view on JLCPCB with 3D view from KiCad.

Bottom side rotates still not quite right

---

plugins/config.py
plugins/process.py

The number of components that are merged into the same row in the BOM file is limited. If there are too many you'll get an "Internal Server Error" when JLCPCB is processing it. 
Their support told me 20 parts per row is the limit but I've tested with 50 and it works, so I split the difference and set it to 30 here. I guess the 20 was only a suggestion :)

Add limit of parts in BOM rows

---

README.md
plugins/process.py

Some footprints can be "double-sided" but in reality once broken into individual parts may need to be strictly on one. An example of a footprint that is used for the top, but a component on the bottom is Kaihl V2 Hotswap key where the bus bar is mounted through the bottom and faces the top.
Currently, there is no way to produce a placement file that accounts for, therefor manual editing of the positions file needs to be done to correct the side.
By implementing a layer override function, similar to what is already done for rotation and position, we can override the kicad footprint and instead have the positions file reflect the expected output that JLCPCB is expecting.
To apply an override open the schematic, then click on a symbol and add the following field `'JLCPCB Layer Override'` …

Add Top and Bottom override on footprints

---

plugins/process.py
plugins/utils.py

[`HasProperty()`](https://docs.kicad.org/doxygen-python-7.0/classpcbnew_1_1FOOTPRINT.html#afd9697816efb46744ef746e94e938dbe) no longer exists on footprints 
and is replaced by [`HasFieldByName()`](https://docs.kicad.org/doxygen-python-nightly/classpcbnew_1_1FOOTPRINT.html#a8ac690e06468caeef7525b056a96545e).
Fixes #84, #97

KiCad 8 compatibility

---

plugins/thread.py

**Store backups as zip instead of new directories. This makes it easier when uploading files in the browser, so that we don't have to keep switching folders and finding were latest production files are. 
Zips are still stored with a timestamp in `backups` subfolder.**
Also fixes orphaned temporary folders in system temp directory. The timestamp in temp folders was probably added for debugging, but original temp folder was never removed.  Fixed by removing the timestamp from temp folders.

Don't change output folder and store backups as zip 

---

README.md
plugins/process.py

Single offset for a given footprint will be applied correctly to all footprint (with different rotations and board side). 
No more `--mixed values--` depending on top/bottom PCB placement. Fixes #101.
Following [example.zip](https://github.com/bennymeg/JLC-Plugin-for-KiCad/files/13932469/test.zip) contains some extra offsets added to footprints. 
Top/bottom without this PR:
Top/bottom with the PR:
Notes: 
- USB-C and diodes have artificial offset added to the footprint.  Notice that top diodes offsets are the same after PR.  However USB-C position offset has changed after PR. This is because position offset should be applied without rotation offset (it depends only on footprint orientation and not final part orientation). And, unlike diodes, USB-C has a rotation offset.
- QFN and DFN …

Consistent top/bottom offsets

---

plugins/process.py

This helps with positioning of thruhole and unspecified component footprint types. 
Unlike the smd type, thru hole components in kicad library have their anchor on pin 1.  This is an issue because it always requires adding position offset to thru hole components before exporting position file. This update uses bounding box center instead of the default anchor to solve this.
Additionally, I compute bounding box center based on copper pads for unspecified footprint types.
It could be done that way for all type of footprints, as I did in this PR https://github.com/Bouni/kicad-jlcpcb-tools/pull/381 but there they were using bounding box center anyways so the change was less drastic. Here we may still want to use kicad anchor for smt for some compatibility reasons. 
I decided to use bounding …

Calculate centroid based on footprint type

---

plugins/process.py

The PlotLayers property has a capital P
(https://gitlab.com/kicad/code/kicad/-/blob/7.0/pcbnew/plotcontroller.h#L98)
hasattr(and internally getattr) is case sensitive.  This resulted in the User.1 layer not being included for v-cuts even if it existed in the project

Fix case of PlotLayers attribute check

---

plugins/process.py

`footprint_has_field(footprint, 'dnp')` returns `False` for DNP components in KiCAD v8.
In KiCAD v8 the DNP flag is available via either the IsDNP() getter or the FP_DNP attribute.
The added `getattr()` call turns into `footprint.IsDNP()` in KiCAD v8 or `bool()` (which evaluates into `False`) in KiCAD v7 and earlier.

Use IsDNP() to get the DNP attribute in KiCAD v8

---

plugins/process.py

Graphics can be stored as footprints - usually with `Unspecified` footprint type. That triggered footprint position calculation based on [pads bounding box centroid](https://github.com/bennymeg/JLC-Plugin-for-KiCad/pull/117) (intended weird footprints imported from other programs, not for graphics).  Graphics don't have pads which was causing Index out of range error. 
Changes:
- skipping footprint without pads - fixes #133
- small refactor (put all skipping conditions in `skip_footprint` var)
- added extra comments (because I was getting confused about my own code).

Footprints without pads fix #133

---

plugins/process.py

The following plot settings are changed to closely match [JLCPCB recommendations](https://jlcpcb.com/help/article/362-how-to-generate-gerber-and-drill-files-in-kicad-7):
- Protel extensions are being used
- Gerber X2 format is explicitly set to false - [caused issues in the past](https://forum.kicad.info/t/apologies-from-atommann-an-engineer-from-jlcpcb-about-gerber-x2-files-at-jlcpcb/26847), even though it might be supported nowadays
Drill settings changed:
- "minimal header" set to false (via `SetOptions`)
- drill units set to "metric" (via `SetFormat(True)`)
- drill map files are being generated and their format is set to Gerber
This fixes #140

fix #140: adjusting plot options and drill options to more closely match JLCPCB recommendations

---

README.md

After struggling for a while to accurately position components in one go, I finally decided to determine the step size of the component move arrows on JLCPCBs website more precisely. It looks like the step size is exactly 1/400 inches, or 0.0635mm.
How I determined this: I created a PCB with a long pin header (C18197918, 11x1 pins, pitch 2.54mm) and uploaded it to JLCPCB (Project files: [JLCPCB_Move_Step_Size.zip](https://github.com/bennymeg/Fabrication-Toolkit/files/15402165/JLCPCB_Move_Step_Size.zip))
After clicking the up button 400x, the connector is moved up like this (or rather, I selected the button via the browser Dev tools & ran `for (i=0;i<400;++i) $0.click()` in the JavaScript console to do it for me):
This is exactly (11-1)x2.54mm, so 1in.

Update JLCPCB position alignment step size

---

plugins/process.py

Tohis should resolve issues like this one https://github.com/bennymeg/Fabrication-Toolkit/pull/138#issuecomment-2203491646 when people use dummy footprints (with no pads) as  a placeholder for actual parts. 
Btw, thanks [bennymeg](https://github.com/bennymeg) for adding `index out of range` protection in bounding box calculation https://github.com/bennymeg/Fabrication-Toolkit/commit/28ea32fedf48da7e14c69d56e46aa0caccb8b498.

Allow footprints with no pads

---

plugins/process.py

It seems JLCPCB has recently changed something about how they process BOM & CPL files: If the board contains any reference designators that are not capitalized, you'll get an error line this:
This change simply applies `.upper()` to all `.GetReference()` calls to ensure the designators are all upper case in the generated files (the error messages are not modified since those are only shown to the user, where the capitalization might be confusing). Since KiCAD anyway complains about duplicate reference designators, even if they differ in capitalization, this should cause any unwanted duplication of reference designators.
Here is the example project used to generate the above error message:
[DesignatorCapitalization.zip](https://github.com/user-attachments/files/17363950/DesignatorCapitaliza …

Capitalize reference designators in generated files

---

plugins/plugin.py

Many dialogs in KiCAD can be closed using the ESC key (Board Setup, Page Settings, DRC etc).
It's a small modification to make the Fabrication Toolkit dialog's behaviour more in phase with other KiCad's dialogs.

Close the dialog when pressing the ESC key

---

README.md
plugins/process.py

Currently, the plugin only supports abbreviating "Part Number" as "Part #" and as "Part". According to Wikipedia, part number is "often abbreviated PN, P/N, part no., or part #". This change adds support for using the abbreviations "PN", "P/N", and "Part No." to better integrate with more workflow stylistic choices.

Add support for addition common abbreviations for part number

---

plugins/cli.py
plugins/thread.py

Hello, firstly thank You for this amazing plugin. I just spined it inside CI and run across small problem with Progress Bar in CLI. When progress bar being printed, in terminal it is shown in one line which is constantly updated. Same does not count for CI, there progres  bar is printed to new line for each update and thus fill log so it become awfully long or hit CI LOG length limit, so another task are not logged.  So I added a argument for disabling it. It's probably  not a best solution, but works quite well for me.  I am open to other ideas.

[Feature] Cli arg for removing progress bar

---

plugins/thread.py

ATM, only the gerber zip-file gets renamed if one specifies a custom name (e.g ${TITLE}_${REVISION}).
The other files like bom.csv are not renamed accordingly.
Hence, they get overwritten every single time.
This path add "_bom.csv",... to the basename if something like ${TITLE}_${REVISION} is given as the archive name in order to preserve the files for each revision.

Rename remaining files if gerber-zip gets a user defined name
